[package]
name = "quaint"
version = "0.1.7"
authors = [
    "Julius de Bruijn <bruijn@prisma.io>",
    "Dominic Petrick <petrick@prisma.io>",
    "Katharina Fey <kookie@spacekookie.de>",
    "Emanuel Jöbstl <emanuel.joebstl@gmail.com>",
    "Tom Houlé <tom@tomhoule.com>"
]
edition = "2018"
readme  = "README.md"
license = "Apache-2.0"
description = "An abstraction layer for SQL databases."
repository  = "https://github.com/prisma/quaint/"
homepage    = "https://github.com/prisma/quaint/"
keywords    = ["mysql", "postgresql", "sqlite", "sql"]
documentation = "https://docs.rs/quaint/"

[package.metadata.docs.rs]
features = [ "full" ]

[features]
default = []

full = ["pooled", "sqlite", "json-1", "postgresql", "uuid-0_8", "chrono-0_4", "mysql"]
full-postgresql = ["pooled", "postgresql", "json-1", "uuid-0_8", "chrono-0_4", "array"]
full-mysql = ["pooled", "mysql", "json-1", "uuid-0_8", "chrono-0_4"]
full-sqlite = ["pooled", "sqlite", "json-1", "uuid-0_8", "chrono-0_4"]

single = ["sqlite", "json-1", "postgresql", "uuid-0_8", "chrono-0_4", "mysql"]
single-postgresql = ["postgresql", "json-1", "uuid-0_8", "chrono-0_4", "array"]
single-mysql = ["mysql", "json-1", "uuid-0_8", "chrono-0_4"]
single-sqlite = ["sqlite", "json-1", "uuid-0_8", "chrono-0_4"]

pooled = ["mobc"]
sqlite = ["rusqlite", "libsqlite3-sys"]
json-1 = ["serde_json"]
postgresql = ["rust_decimal/postgres", "native-tls", "tokio-postgres", "postgres-native-tls", "array", "bytes", "tokio"]
uuid-0_8 = ["uuid"]
chrono-0_4 = ["chrono"]
mysql = ["mysql_async"]
tracing-log = ["tracing", "tracing-core"]
array = []

[dependencies]
url = "1.7"
metrics = "0.11"
percent-encoding = "2"
debug_stub_derive = "0.3"
lazy_static = "1.3"
num_cpus = "1.11"
rust_decimal = "1.1"
futures = "0.3"
thiserror = "1.0"

uuid = { version = "0.8", optional = true }
chrono = { version = "0.4", optional = true }
serde_json = { version = "1.0", optional = true }

rusqlite = { version = "0.21", features = ["chrono", "bundled"], optional = true }
libsqlite3-sys = { version = "0.17", default-features = false, features = ["bundled"], optional = true }

tokio-postgres = { version = "0.5", features = ["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1"], optional = true }
postgres-native-tls = { version = "0.3", optional = true }
native-tls = { version = "0.2", optional = true }

mysql_async = { version = "0.21", optional = true }

log = { version = "0.4", features = ["release_max_level_trace"] }
tracing = { version = "0.1", optional = true }
tracing-core = { version = "0.1", optional = true }

mobc = { version = "0.3", optional = true }
bytes = { version = "0.5", optional = true }
tokio = { version = "0.2", features = ["rt-threaded", "macros"], optional = true}

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-threaded", "macros"]}
