[package]
authors = [
  "Julius de Bruijn <bruijn@prisma.io>",
  "Katharina Fey <kookie@spacekookie.de>",
  "Tom Houlé <tom@tomhoule.com>",
  "Emanuel Jöbstl <emanuel.joebstl@gmail.com>",
  "Matthias Oertel <oertel@prisma.io>",
  "Dominic Petrick <petrick@prisma.io>",
]
description = "An abstraction layer for SQL databases."
documentation = "https://docs.rs/quaint/"
edition = "2018"
homepage = "https://github.com/prisma/quaint/"
keywords = ["mysql", "postgresql", "sqlite", "sql"]
license = "Apache-2.0"
name = "quaint"
readme = "README.md"
repository = "https://github.com/prisma/quaint/"
version = "0.2.0-alpha.13"

[package.metadata.docs.rs]
features = ["docs", "all"]

[features]
default = []
docs = []

all = [
  "chrono",
  "json",
  "mssql",
  "mysql",
  "pooled",
  "postgresql",
  "serde-support",
  "sqlite",
  "uuid",
  "bigdecimal"
]

postgresql = [
  "native-tls",
  "tokio-postgres",
  "postgres-types",
  "postgres-native-tls",
  "bytes",
  "tokio",
  "bit-vec",
  "lru-cache",
  "byteorder",
]

json = ["serde_json", "base64"]
mssql = ["tiberius", "uuid", "chrono", "tokio-util", "tokio/time", "tokio/net", "either"]
mysql = ["mysql_async", "tokio/time"]
pooled = ["mobc"]
serde-support = ["serde", "chrono/serde"]
sqlite = ["rusqlite", "libsqlite3-sys", "tokio/sync"]
tracing-log = ["tracing", "tracing-core"]
bigdecimal = ["bigdecimal_", "num-bigint"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
hex = "0.4"
metrics = "0.12"
num_cpus = "1.12"
once_cell = "1.3"
percent-encoding = "2"
thiserror = "1.0"
url = "2.1"

either = { version = "1.6", optional = true }
byteorder = { default-features = false, optional = true, version = "1.3" }
base64 = { version = "0.11.0", optional = true }
chrono = { version = "0.4", optional = true }
lru-cache = { version = "0.1", optional = true }
serde_json = { version = "1.0.48", optional = true }
rusqlite = { version = "0.23", features = ["chrono", "bundled"], optional = true }
native-tls = { version = "0.2", optional = true }
mysql_async = { version = "0.24.2", optional = true }
log = { version = "0.4", features = ["release_max_level_trace"] }
tracing = { version = "0.1", optional = true }
tracing-core = { version = "0.1", optional = true }
bit-vec = { version = "0.6.1", optional = true }
bytes = { version = "0.5", optional = true }
mobc = { version = "0.5.7", optional = true }
serde = { version = "1.0", optional = true }
connection-string = "0.1.10"

[dev-dependencies]
indoc = "0.3"
names = "0.11"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
test-macros = { path = "test-macros" }
test-setup = { path = "test-setup" }
uuid = { version = "0.8", features = ["v4"] }
tokio = { version = "0.2", features = ["rt-threaded", "macros", "io-driver", "time"] }

[dependencies.bigdecimal_]
version = "0.2.0"
optional = true
package = "bigdecimal"

[dependencies.num-bigint]
version = "0.3.0"
default-features = false
optional = true
features = ["std"]

[dependencies.uuid]
version = "0.8"
optional = true

[dependencies.tiberius]
version = "0.4.16"
features = ["sql-browser-tokio", "chrono", "bigdecimal"]
optional = true

[dependencies.tokio-postgres]
branch = "pgbouncer-mode"
features = ["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1", "with-bit-vec-0_6"]
git = "https://github.com/pimeys/rust-postgres"
optional = true

[dependencies.postgres-types]
branch = "pgbouncer-mode"
features = ["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1", "with-bit-vec-0_6"]
git = "https://github.com/pimeys/rust-postgres"
optional = true

[dependencies.postgres-native-tls]
branch = "pgbouncer-mode"
git = "https://github.com/pimeys/rust-postgres"
optional = true

[dependencies.libsqlite3-sys]
version = "0.18"
default-features = false
features = ["bundled"]
optional = true

[dependencies.tokio]
version = "0.2"
features = ["rt-threaded", "macros", "sync"]
optional = true

[dependencies.tokio-util]
version = "0.3"
features = ["compat"]
optional = true
