(function() {var implementors = {};
implementors["prisma_query"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"prisma_query/ast/struct.Column.html\" title=\"struct prisma_query::ast::Column\">Column</a>",synthetic:false,types:["prisma_query::ast::column::Column"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"prisma_query/ast/enum.ConditionTree.html\" title=\"enum prisma_query::ast::ConditionTree\">ConditionTree</a>",synthetic:false,types:["prisma_query::ast::conditions::ConditionTree"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"prisma_query/ast/struct.Over.html\" title=\"struct prisma_query::ast::Over\">Over</a>",synthetic:false,types:["prisma_query::ast::function::Over"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"prisma_query/ast/struct.RowNumber.html\" title=\"struct prisma_query::ast::RowNumber\">RowNumber</a>",synthetic:false,types:["prisma_query::ast::function::RowNumber"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"prisma_query/ast/struct.Ordering.html\" title=\"struct prisma_query::ast::Ordering\">Ordering</a>",synthetic:false,types:["prisma_query::ast::ordering::Ordering"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"prisma_query/ast/struct.Row.html\" title=\"struct prisma_query::ast::Row\">Row</a>",synthetic:false,types:["prisma_query::ast::row::Row"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"prisma_query/ast/struct.Select.html\" title=\"struct prisma_query::ast::Select\">Select</a>",synthetic:false,types:["prisma_query::ast::select::Select"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
