name: Cargo tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - name: Install dependencies
        run: sudo apt install -y openssl libkrb5-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features=all

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  cargo-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        features:
          - "--lib --features=all"
          - "--lib --no-default-features --features=sqlite"
          - "--lib --no-default-features --features=sqlite --features=chrono --features=json --features=uuid --features=pooled --features=serde-support --features=bigdecimal"
          - "--lib --no-default-features --features=postgresql"
          - "--lib --no-default-features --features=postgresql --features=chrono --features=json --features=uuid --features=pooled --features=serde-support --features=bigdecimal"
          - "--lib --no-default-features --features=mysql"
          - "--lib --no-default-features --features=mysql --features=chrono --features=json --features=uuid --features=pooled --features=serde-support --features=bigdecimal"
          - "--lib --no-default-features --features=mssql"
          - "--lib --no-default-features --features=mssql --features=chrono --features=json --features=uuid --features=pooled --features=serde-support --features=bigdecimal"
          - "--doc --features=all"
    env:
      TEST_MYSQL: "mysql://root:prisma@localhost:3306/prisma"
      TEST_MYSQL8: "mysql://root:prisma@localhost:3307/prisma"
      TEST_PSQL: "postgres://postgres:prisma@localhost:5432/postgres"
      TEST_MSSQL: "jdbc:sqlserver://localhost:1433;database=master;user=SA;password=<YourStrong@Passw0rd>;trustServerCertificate=true"
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.features }}

      - name: Start Databases
        run: docker-compose -f docker-compose.yml up -d

      - name: Sleep for 20s
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s

      - name: Run tests
        run: cargo test ${{ matrix.features }}

  rustdoc:
    needs: [clippy, format, cargo-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: linux-cargo-rustdoc

      - name: Generate documentation
        run: |
          cargo rustdoc --all-features
      - name: Commit changes
        run: |
          git config user.name "GitHub agent"
          git config user.email "hello@prisma.io"

          rm -rf deploy_docs
          git clone --branch gh-pages "git@github.com:prisma/quaint.git" deploy_docs > /dev/null 2>&1
          rm -rf deploy_docs/*
          mv target/doc/* deploy_docs/
          echo "<meta http-equiv=refresh content=0;url=quaint/index.html>" > deploy_docs/index.html

          DIFF=$(git status -s)
          printf "$DIFF\n"

          if [ -z "$DIFF" ]
          then
              echo "Nothing to do"
          else
              git -C deploy_docs add -A .
              git -C deploy_docs commit -m "Add changes"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: deploy_docs
